#!/usr/bin/env python3
"""make_web_qr.py — bake Micro QR matrices into web/qr-data.js.

The daemon builds QR codes at runtime with segno (a real Micro QR encoder,
~2k lines of Reed-Solomon, masking and format-info BCH). The web page has no
Python and no network, so it cannot. Porting segno to JS is a genuine project
and a wrong encoder produces an unscannable code — worse than no code at all,
and invisible without a phone to test it.

So: bake the matrices here, where segno is the reference implementation and
the output is correct by construction. The web page renders a lookup.

Arbitrary text still needs the daemon (`blockctl qr "anything"`). The web
page's QR button has always sent a fixed payload, so a lookup covers it.

    .venv/bin/python3 tools/make_web_qr.py                # default payloads
    .venv/bin/python3 tools/make_web_qr.py HELLO WORLD    # add your own

M3 is exactly 15x15 — the glass — and the dark bezel is the quiet zone.
"""

from __future__ import annotations

import sys
from pathlib import Path

W = H = 15
DEFAULT_PAYLOADS = ["CLAWDPAD"]
OUT = Path(__file__).resolve().parent.parent / "web" / "qr-data.js"


def bake(data: str) -> list[str]:
    """segno matrix → 15 strings of 15 chars ('#' = dark module = lit pixel)."""
    import segno

    q = segno.make(data, micro=True)
    m = [list(row) for row in q.matrix]
    if len(m) > H or len(m[0]) > W:
        raise SystemExit(f"payload too big for the glass ({data!r} → "
                         f"{len(m)}x{len(m[0])}, max {H}x{W})")

    pad = (H - len(m)) // 2  # M1/M2 come out smaller; centre them like the daemon
    grid = [["." for _ in range(W)] for _ in range(H)]
    for y, row in enumerate(m):
        for x, v in enumerate(row):
            grid[y + pad][x + pad] = "#" if v else "."
    print(f"  {data!r}: {q.version} error={q.error} mode={q.mode} "
          f"{len(m)}x{len(m[0])}" + (f" (padded by {pad})" if pad else ""))
    return ["".join(r) for r in grid]


def main() -> int:
    payloads = sys.argv[1:] or DEFAULT_PAYLOADS
    print(f"baking {len(payloads)} payload(s) with segno:")
    baked = {p: bake(p) for p in payloads}

    lines = [
        "/* GENERATED by tools/make_web_qr.py — do not hand-edit.",
        " *",
        " * Micro QR matrices, baked because the tab has no encoder. '#' is a",
        " * dark module, which the glass renders LIT (an inverted QR; scanners",
        " * handle it). Regenerate with:",
        " *     .venv/bin/python3 tools/make_web_qr.py",
        " *",
        " * Arbitrary text needs the daemon: blockctl qr \"your text\"",
        " */",
        "const QR_BAKED = {",
    ]
    for payload, rows in baked.items():
        lines.append(f"  {payload!r}: [".replace("'", '"'))
        lines += [f'    "{r}",' for r in rows]
        lines.append("  ],")
    lines += [
        "};",
        "",
        "if (typeof module !== \"undefined\") module.exports = { QR_BAKED };",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(baked)} payload(s))")
    return 0


if __name__ == "__main__":
    sys.exit(main())
