/* GENERATED by tools/make_web_qr.py — do not hand-edit.
 *
 * Micro QR matrices, baked because the tab has no encoder. '#' is a
 * dark module, which the glass renders LIT (an inverted QR; scanners
 * handle it). Regenerate with:
 *     .venv/bin/python3 tools/make_web_qr.py
 *
 * Arbitrary text needs the daemon: blockctl qr "your text"
 */
const QR_BAKED = {
  "CLAWDPAD": [
    "#######.#.#.#.#",
    "#.....#.###...#",
    "#.###.#.#####..",
    "#.###.#.#...###",
    "#.###.#..##.#..",
    "#.....#...##..#",
    "#######..##.#..",
    ".........##....",
    "#...#..##.....#",
    "..#.######.#...",
    "####....#..#.##",
    "..##.#...#.##.#",
    "#..##..##.#.#.#",
    "..####..####..#",
    "#..######.####.",
  ],
};

if (typeof module !== "undefined") module.exports = { QR_BAKED };
